name: Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: fileinfo, pdo, simplexml
          tools: composer:v2

      - name: Validate composer config
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Composer security audit
        run: composer audit:composer

      - name: Install yamllint
        run: python -m pip install --user yamllint

      - name: YAML lint
        run: composer lint:yaml

      - name: PHP CS check
        run: composer lint:php

      - name: PHPStan
        run: composer analyze:php
